name: win_ui
version: 1.0.0+1
publish_to: none
description: win 10 use fluent ui
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.1
  fluent_ui: ^3.9.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

