name: flutter_rust_bridge_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: ^1.41.0
  fluent_ui: ^4.0.0-pre.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  ffi: ^2.0.1

dev_dependencies: 
  ffigen: ^6.0.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

