name: flutter_rust_bridge_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: ^1.41.2
  fluent_ui: ^4.0.0-pre.3
  get: ^4.6.5
  ffi: ^2.0.1
  file_picker: ^5.0.1
  flutter_quill: ^5.4.1

dev_dependencies:
  ffigen: ^6.1.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
