name: mh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  http: ^0.13.4
  get: ^4.6.5
  get_storage: ^2.0.3
  lottie: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie_animations/
  uses-material-design: true

