name: flutter_rust_bridge_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.45.0
  get: ^4.6.5
  fluent_ui: ^4.0.0-pre.4
  chewie: ^1.3.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  video_player: ^2.4.5
  video_player_android: ^2.3.8
  video_player_avfoundation: ^2.3.5
  video_player_platform_interface: ^5.1.3
  video_player_web: ^2.0.12
  video_player_macos: ^1.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
