name: flutter_rust_bridge_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.45.0
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
