export 'bind_mobile_page1.dart'; // 第三方登录后绑定手机号页面
export 'bind_mobile_page2.dart'; // 第三方登录后绑定手机号页面
export 'forget_password_page1.dart'; // 忘记密码第一步：输入手机号
export 'forget_password_page2.dart'; // 忘记密码第二步：输入验证码
export 'forget_password_page3.dart'; // 忘记密码第三步：输入新密码
export 'login_page.dart'; // 注册登录-手机号密码登录
export 'mobile_page.dart'; // 注册登录-验证码登陆/注册
export 'registration_page.dart'; // 测试页面
export 'verification_code_page.dart'; // 填写验证码页面
